site_name: ZCETHAN's Blog
site_url: https://localhost:8000/mysite
theme:
  name: material
  language: zh
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      accent: cyan
      primary: indigo

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      accent: cyan
      primary: indigo
  features:
    - navigation.tabs
    - navigation.prune
    - navigation.top

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg